/* 定义项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.13.0 on Mon Feb 10 20:01:52 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_hello_server_h_)
#define _c_hello_server_h_

#include "hello_common.h"

#if defined(__cplusplus)
extern "C"
{
#endif

typedef void * erpc_service_t;

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief DEMO identifiers */
enum _DEMO_ids
{
    kDEMO_service_id = 1,
    kDEMO_hello_world_id = 1,
    kDEMO_say_message_id = 2,
    kDEMO_erpc_add_id = 3,
};

/*! 定义服务接口函数 */
//! @name DEMO
//@{
void hello_world(void);

void say_message(const char * msg);

int32_t erpc_add(int32_t data1, int32_t data2);
//@}


#endif // ERPC_FUNCTIONS_DEFINITIONS

/*! @brief Return DEMO_service service object. */
erpc_service_t create_DEMO_service(void);

/*! @brief Destroy DEMO_service service object. */
void destroy_DEMO_service(erpc_service_t service);


#if defined(__cplusplus)
}
#endif

#endif // _c_hello_server_h_
