/* 定义项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.13.0 on Mon Feb 10 20:01:52 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_hello_client_h_)
#define _c_hello_client_h_

#include "hello_common.h"
#include "erpc_client_manager.h"

#if defined(__cplusplus)
extern "C"
{
#endif

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief DEMO identifiers */
enum _DEMO_ids
{
    kDEMO_service_id = 1,
    kDEMO_hello_world_id = 1,
    kDEMO_say_message_id = 2,
    kDEMO_erpc_add_id = 3,
};

/*! 定义服务接口函数 */
//! @name DEMO
//@{
void hello_world(void);

void say_message(const char * msg);

int32_t erpc_add(int32_t data1, int32_t data2);
//@}

#endif // ERPC_FUNCTIONS_DEFINITIONS

void initDEMO_client(erpc_client_t client);

void deinitDEMO_client(void);

#if defined(__cplusplus)
}
#endif

#endif // _c_hello_client_h_
