/* 定义项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.13.0 on Mon Feb 10 20:01:52 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_hello_interface_hpp_)
#define _hello_interface_hpp_

#include "hello_common.hpp"

namespace erpcShim
{


// Abstract base class for DEMO
class DEMO_interface
{
    public:
        static const uint8_t m_serviceId = 1;
        static const uint8_t m_hello_worldId = 1;
        static const uint8_t m_say_messageId = 2;
        static const uint8_t m_erpc_addId = 3;

        virtual ~DEMO_interface(void);

        virtual void hello_world(void) = 0;

        virtual void say_message(const char * msg) = 0;

        virtual int32_t erpc_add(int32_t data1, int32_t data2) = 0;
private:
};
} // erpcShim


#endif // _hello_interface_hpp_
