/* 定义项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.13.0 on Mon Feb 10 20:01:52 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_hello_server_hpp_)
#define _hello_server_hpp_

#include "hello_interface.hpp"

#include "erpc_server.hpp"
#include "erpc_codec.hpp"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


namespace erpcShim
{

/*!
 * @brief Service subclass for DEMO.
 */
class DEMO_service : public erpc::Service
{
public:
    DEMO_service(DEMO_interface *_DEMO_interface);

    virtual ~DEMO_service();

    /*! @brief return service interface handler. */
    DEMO_interface* getHandler(void);

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport);

private:
    DEMO_interface *m_handler;
    /*! @brief Server shim for hello_world of DEMO interface. */
    erpc_status_t hello_world_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);

    /*! @brief Server shim for say_message of DEMO interface. */
    erpc_status_t say_message_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);

    /*! @brief Server shim for erpc_add of DEMO interface. */
    erpc_status_t erpc_add_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);
};

} // erpcShim


#endif // _hello_server_hpp_
