/* 定义项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.13.0 on Mon Feb 10 20:01:52 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_hello_client_hpp_)
#define _hello_client_hpp_

#include "hello_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class DEMO_client: public DEMO_interface
{
    public:
        DEMO_client(erpc::ClientManager *manager);

        virtual ~DEMO_client();

        virtual void hello_world(void);

        virtual void say_message(const char * msg);

        virtual int32_t erpc_add(int32_t data1, int32_t data2);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _hello_client_hpp_
